apiVersion: v1
kind: Pod
metadata:
  name: livenessprobe
  labels:
    name: livenessprobe
spec:
  containers:
  - name: my-nginx-container
    image: nginx:alpine
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    livenessProbe:
      httpGet:
          path: /index.html
          port: 80
