apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: mycronjob
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          name: my-job-from-cronjob
        spec:
          containers:
            - name: my-job-container
              image: nginx:alpine
              command:
                - /bin/sh
                - "-c"
                - "date; echo Hello from the Kubernetes cluster"
          restartPolicy: OnFailure

  
